### PR TITLE
20201221

### PR DESCRIPTION
**Pull request by kompotkot**

### CODE REVIEW

**Comment by kompotkot** [comment]
@kompotkot summarize

**Comment by kompotkot** [comment]
@kompotkot summarize

**Comment by kompotkot** [comment]
@kompotkot check 
- [x] One
- [x] Two

**Comment by kompotkot** [comment]
@kompotkot summarize

**Comment by kompotkot** [comment]
@kompotkot summarize

**Comment by kompotkot** [comment]
@kompotkot summarize

**Comment by kompotkot** [comment]
@kompotkot check 
- [ ] One
- [ ] Two

**Comment by kompotkot** [comment]
@kompotkot summarize

**Comment by kompotkot** [comment]
@kompotkot check 
- [ ] One
- [x] Two

**Comment by kompotkot** [comment]
@kompotkot summarize

**Comment by kompotkot** [comment]
@kompotkot summarize

**Comment by kompotkot** [comment]
@kompotkot summarize

**Comment by kompotkot** [comment]
@kompotkot summarize

**Comment by kompotkot** [comment]
@kompotkot summarize

**Comment by kompotkot** [comment]
@kompotkot summarize

**Comment by kompotkot** [comment]
@kompotkot summarize

**Comment by kompotkot** [comment]
@kompotkot check 
- [ ] One
- [ ] Two

**Comment by kompotkot** [comment]
@kompotkot check 
- [ ] One
- [ ] Two

**Comment by kompotkot** [comment]
@kompotkot summarize

**Comment by kompotkot** [comment]
@kompotkot summarize

**Comment by kompotkot** [comment]
@kompotkot check 
- [x] One
- [x] Two

**Comment by kompotkot** [comment]
@kompotkot summarize

**Comment by kompotkot** [comment]
@kompotkot check 
- [ ] One
- [ ] Two

**Comment by kompotkot** [comment]
@kompotkot check 
- [ ] One
- [ ] Two

**Comment by kompotkot** [comment]
@kompotkot summarize

**Comment by zomglings** [comment]
@bugout-dev summarize

**Comment by zomglings** [comment]
@kompotkot summarize

**Comment by kompotkot** [comment]
@kompotkot check 
- [ ] One
- [ ] Two

**Comment by kompotkot** [comment]
@kompotkot summarize

**Comment by kompotkot** [comment]
@kompotkot summarize

**Comment by kompotkot** [comment]
<html><body><h2><a href="https://github.com/simiotics/locust">Locust</a> summary</h2><h3>Git references</h3><b>Initial: </b><span>8ea759d</span><br><b>Terminal: </b><span>717d9a7</span><br><hr><div><details><summary><a href="test/2.py">test/2.py</a></summary><div><b>Changes:</b><ul><li><b>function</b><span> </span><a href="test/2.py">func222</a><b> changed lines: </b><span>1</span><span>/</span><span>2</span><ul></ul></li></ul></div></details></div></body></html>

**Pull request closed without merging**
