### PR TITLE
20201203

### PR DESCRIPTION
**Pull request by kompotkot**

### CODE REVIEW

**Comment by kompotkot** [comment]
@kompotkot summarize

**Comment by kompotkot** [comment]
@kompotkot summarize

**Comment by kompotkot** [comment]
@kompotkot summarize

**Comment by kompotkot** [comment]
@kompotkot summarize

**Comment by kompotkot** [comment]
@kompotkot summarize

**Comment by kompotkot** [comment]
* [ ] foo
    * [x] bar
    * [ ] baz

**Comment by kompotkot** [comment]
@kompotkot check require block2

**Comment by kompotkot** [comment]
[ ] check

**Comment by kompotkot** [comment]
- [ ] check

**Comment by kompotkot** [comment]
- [ ] check
- [ ] 23

**Comment by kompotkot** [comment]
- [ ] check
- [ ] 23

**Comment by kompotkot** [comment]
@kompotkot
- [ ] check
- [ ] 23

**Comment by kompotkot** [comment]
@kompotkot check
- [ ] check
- [ ] 23

**Comment by kompotkot** [comment]
@kompotkot check accept block2

**Comment by kompotkot** [comment]
@kompotkot check accept block2

**Comment by kompotkot** [comment]
@kompotkot check accept block2

**Comment by kompotkot** [comment]
@kompotkot check accept block2

**Comment by kompotkot** [comment]
@kompotkot check require block3

**Comment by kompotkot** [comment]
@kompotkot check require block3

**Comment by kompotkot** [comment]
@kompotkot check accepted block3

**Comment by kompotkot** [comment]
@kompotkot check accept block3

**Comment by kompotkot** [comment]
@kompotkot check accept

**Comment by kompotkot** [comment]
@kompotkot check
- [x] Migration 1
- [x] Database 2
- [x] block

**Comment by kompotkot** [comment]
@kompotkot check accept Database 2

**Comment by kompotkot** [comment]
@kompotkot check require block3

**Comment by kompotkot** [comment]
@kompotkot check accept block3

**Comment by kompotkot** [comment]
@kompotkot check require block3

**Comment by kompotkot** [comment]
@kompotkot check accept block3

**Comment by kompotkot** [comment]
@kompotkot check
- [x] Migration 1
- [x] Database 2

**Comment by kompotkot** [comment]
@kompotkot check
- [x] Migration 1
- [x] Database 2

**Comment by kompotkot** [comment]
@kompotkot check
- [x] Migration 1
- [ ] Database 2

**Comment by kompotkot** [comment]
@kompotkot check require Alembic migration

**Comment by kompotkot** [comment]
@kompotkot check
- [ ] Migration 1
- [x] Database 2

**Comment by kompotkot** [comment]
@kompotkot check accept Migration 1

**Comment by kompotkot** [comment]
@kompotkot check accept Alembic migration

**Comment by kompotkot** [comment]
@kompotkot check accept Migration 1

**Comment by kompotkot** [comment]
@kompotkot check require test2

**Comment by kompotkot** [comment]
@kompotkot check accept test2

**Comment by kompotkot** [comment]
@kompotkot check
- [ ] Migration 1
- [ ] Variables 2

**Comment by kompotkot** [comment]
@kompotkot check
- [ ] Migration 1
- [ ] Variables 2

**Comment by kompotkot** [comment]
@kompotkot check
- [ ] Migration 1
- [ ] Variables 2

**Comment by kompotkot** [comment]
@kompotkot check
- [x] Migration 13
- [x] Variables 23

**Comment by kompotkot** [comment]
@kompotkot check accept Migration 1

**Comment by kompotkot** [comment]
@kompotkot check require Variables 23

**Comment by kompotkot** [comment]
@kompotkot check require Variables 23

**Comment by kompotkot** [comment]
@kompotkot check
- [x] Migration
- [x] Variables

**Comment by kompotkot** [comment]
@kompotkot check accept Variables 23

**Comment by kompotkot** [comment]
@kompotkot check
- [x] Migration
- [x] Variables

**Comment by kompotkot** [comment]
@kompotkot check require Variables 2

**Comment by serhgmail** [comment]
@kompotkot check
- [ ] Migration
- [x] Variables

**Comment by kompotkot** [comment]
@kompotkot check require Variables 2

**Comment by kompotkot** [comment]
@kompotkot check require Variables 2

**Comment by serhgmail** [comment]
@kompotkot check require Variables 3

**Comment by kompotkot** [comment]
@kompotkot check accept Variables 2

**Comment by serhgmail** [comment]
@kompotkot check
- [x] Migration
- [x] Variables

**Comment by kompotkot** [comment]
@bugout-dev check require 123

**Comment by kompotkot** [comment]
@kompotkot summarize

**Comment by kompotkot** [comment]
@kompotkot check require Test

**Comment by kompotkot** [comment]
@kompotkot check
- [ ] Migration
- [ ] Variables

**Comment by kompotkot** [comment]
@kompotkot summarize

**Comment by kompotkot** [comment]
@kompotkot check
- [ ] Migration
- [ ] Variables

**Comment by kompotkot** [comment]
@kompotkot summarize

**Comment by kompotkot** [comment]
@kompotkot check
- [x] Migration
- [x] Variables

**Comment by kompotkot** [comment]
@kompotkot summarize

**Pull request closed without merging**
